let card_data = [
  [
    {
      address: "chennai",
      name: "steffy Makeup",
      user_email: "madhubala1@gmail.com",
      artist_password: "78",
      confirm_pass: "78",
      ruppi: "10000",
      localty: "chennai",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "12",
      image_url: "https://iili.io/HXGZPUu.jpg",
      services: [
        { category: "Nude", values: ["1"], useremail: "madhubala1@gmail.com" },
        { category: "Hd", values: ["2"], useremail: "madhubala1@gmail.com" },
        {
          category: "celebirity",
          values: ["7"],
          useremail: "madhubala1@gmail.com",
        },
        {
          category: "Editorial",
          values: ["6"],
          useremail: "madhubala1@gmail.com",
        },
      ],
      user_name: "steffy Makeup",
      artits_bio: "\n    I am a artist from 2010",
      number: "6369421401",
      location: {},
      experince: "12",
      price: "10000",
      Language: "tamil",
      social_media_account: "sstefyy@its..",
    },
    {
      address: "12/a kanyakumari",
      name: "subha makeup",
      user_email: "madhubala99@gmail.com",
      artist_password: "Madhu.06",
      confirm_pass: "Madhu.06",
      ruppi: "10000",
      localty: "Kanyakumari",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "12",
      image_url: "https://iili.io/H8I7QKN.jpg",
      services: [
        { category: "Nude", values: ["1"], useremail: "madhubala99@gmail.com" },
        { category: "Hd", values: ["2"], useremail: "madhubala99@gmail.com" },
        {
          category: "Matte",
          values: ["3"],
          useremail: "madhubala99@gmail.com",
        },
        {
          category: "shymmery",
          values: ["8"],
          useremail: "madhubala99@gmail.com",
        },
        {
          category: "celebirity",
          values: ["7"],
          useremail: "madhubala99@gmail.com",
        },
        {
          category: "Natural",
          values: ["10"],
          useremail: "madhubala99@gmail.com",
        },
      ],
      packages: [
        {
          "sare_drapping+Advance Makeup per person": "12000",
          "Pro Makeup+Basic hair style Per person": "0",
          "Jewelery+HD Makeup per person": "0",
          "Pro Makeup+custumes Per Person": "0",
          "Bride+BrideMade 2 Person": "00",
          "Hd Makeup+Hair style per person": "",
          "Heavy Makeup+jwelers+custumes": "00",
          "Hair style+light touchup": "0",
          "Makeup+mehandi": "0",
          artist_name: "subha makeup",
          id: 0,
          email: "madhubala99@gmail.com",
        },
        {
          "sare_drapping+Advance Makeup per person": "40022",
          "Pro Makeup+Basic hair style Per person": "12000",
          "Jewelery+HD Makeup per person": "18000",
          "Pro Makeup+custumes Per Person": "36000",
          "Bride+BrideMade 2 Person": "35000",
          "Hd Makeup+Hair style per person": "13000",
          "Heavy Makeup+jwelers+custumes": "19000",
          "Hair style+light touchup": "20000",
          "Makeup+mehandi": "34000",
          artist_name: "subha makeup",
          id: 0,
          email: "madhubala99@gmail.com",
        },
      ],
      booking_records: [
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "765432456789",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-30",
          time: "00:25",
          status: false,
          id: 0,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "987654",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "05:25",
          status: false,
          id: 1,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "234",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "14:36",
          status: false,
          selected_event: "Bridal",
          id: 2,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "123456",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-31",
          time: "06:09",
          status: false,
          selected_event: "Bridal",
          id: 3,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "123456",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-31",
          time: "06:09",
          status: false,
          selected_event: "Bridal",
          id: 4,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "123456",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-31",
          time: "06:09",
          status: false,
          selected_event: "Bridal",
          id: 5,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "9876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-15",
          time: "05:32",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 6,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "987654323456789",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-16",
          time: "04:40",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 7,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "9876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-22",
          time: "06:46",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 60000,
          id: 8,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "098765",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-22",
          time: "05:47",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 60000,
          id: 9,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "89765",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-22",
          time: "07:49",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 10,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "9876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "06:52",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 11,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "9876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-22",
          time: "06:55",
          status: false,
          selected_event: "Birthday",
          se: ["Jewelery+HD Makeup per person"],
          totla_cost: 60000,
          id: 12,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "09876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-17",
          time: "05:58",
          status: false,
          selected_event: "Birthday",
          se: ["Jewelery+HD Makeup per person"],
          totla_cost: 60000,
          id: 13,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "09876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-30",
          time: "03:05",
          status: false,
          selected_event: "Birthday",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 20000,
          id: 14,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "09876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-22",
          time: "03:05",
          status: false,
          selected_event: "Birthday",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 20000,
          id: 15,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "987654",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-30",
          time: "06:04",
          status: false,
          selected_event: "Birthday",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 16,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "7654567890",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "08:07",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 40000,
          id: 17,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "6369421401",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-30",
          time: "17:05",
          status: false,
          selected_event: "Bridal",
          se: [
            "sare_drapping+Advance Makeup per person",
            "Bride+BrideMade 2 Person",
          ],
          totla_cost: 80000,
          id: 18,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "9876543456",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-15",
          time: "04:01",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 80044,
          id: 19,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "876543",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-30",
          time: "03:05",
          status: false,
          selected_event: "Birthday",
          se: ["Pro Makeup+Basic hair style Per person"],
          totla_cost: 24000,
          id: 20,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "0987654",
          customer_address: "chennai",
          event_date: "2023-05-30",
          time: "13:52",
          status: false,
          selected_event: "Bridal",
          se: ["sare_drapping+Advance Makeup per person"],
          totla_cost: 80044,
          id: 21,
          selected_artist_for_booking: "subha makeup",
        },
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "09",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "16:11",
          status: false,
          selected_event: "Bridal",
          se: ["Pro Makeup+custumes Per Person"],
          totla_cost: 72000,
          id: 22,
          selected_artist_for_booking: "subha makeup",
        },
      ],
      user_name: "subha makeup",
      number: "6369421401",
      location: {},
      experince: "12",
      price: "10000",
      artits_bio: "\n    I am amakeup artist since 2010\n",
      Language: "tamil",
      social_media_account: "subaha queen",
    },
    {
      address: "Trichy,samyapuram",
      name: "Janani Makeup",
      user_email: "janani@gmail.com",
      artist_password: "jan123.",
      confirm_pass: "jan123.",
      ruppi: "15000",
      localty: "Trichy",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "11",
      image_url: "https://iili.io/H8IYufV.jpg",
      services: [
        {
          category: "celebirity",
          values: ["7"],
          useremail: "janani@gmail.com",
        },
        { category: "shymmery", values: ["8"], useremail: "janani@gmail.com" },
        { category: "Natural", values: ["10"], useremail: "janani@gmail.com" },
        { category: "Permanent", values: ["9"], useremail: "janani@gmail.com" },
      ],
      packages: [
        {
          cost_1: "",
          cost_2: "",
          cost_3: "",
          cost_4: "",
          cost_5: "",
          cost_6: "",
          cost_7: "",
          cost_8: "",
          cost_9: "23",
          artist_name: "Janani Makeup",
          id: 0,
          email: "janani@gmail.com",
        },
      ],
    },
    {
      address: "12/a salem",
      name: "Priya Makeup",
      user_email: "priya99@gmail.com",
      artist_password: "priya.123",
      confirm_pass: "priya.123",
      ruppi: "18000",
      localty: "salem",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "8",
      image_url: "https://iili.io/H8IYEsR.jpg",
      services: [
        { category: "Hd", values: ["2"], useremail: "priya99@gmail.com" },
        { category: "shymmery", values: ["8"], useremail: "priya99@gmail.com" },
        {
          category: "celebirity",
          values: ["7"],
          useremail: "priya99@gmail.com",
        },
      ],
    },
    {
      address: "12/a namakal",
      name: "Queency Makeup",
      user_email: "queen99@gmail.com",
      artist_password: "queen.123",
      confirm_pass: "queen.123",
      ruppi: "18000",
      localty: "namakal",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "8",
      image_url: "https://iili.io/H8IYezG.webp",
      services: [
        { category: "Hd", values: ["2"], useremail: "queen99@gmail.com" },
        { category: "Dewy", values: ["4"], useremail: "queen99@gmail.com" },
        {
          category: "Editorial",
          values: ["6"],
          useremail: "queen99@gmail.com",
        },
      ],
      packages: [
        {
          sare_drapping: "10000",
          hdMakeup: "120000",
          cost_3: "",
          cost_4: "",
          cost_5: "",
          cost_6: "",
          cost_7: "",
          cost_8: "",
          cost_9: "",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
        {
          sare_drapping: "",
          hdMakeup: "",
          cost_3: "345",
          cost_4: "2345",
          cost_5: "2134",
          cost_6: "234",
          cost_7: "233234",
          cost_8: "33434",
          cost_9: "3434",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
        {
          sare_drapping: "87654",
          hdMakeup: "987654",
          cost_3: "345",
          cost_4: "2345",
          cost_5: "2134",
          cost_6: "234",
          cost_7: "233234",
          cost_8: "33434",
          cost_9: "3434",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
        {
          sare_drapping: "87654",
          hdMakeup: "987654",
          cost_3: "345",
          cost_4: "2345",
          cost_5: "2134",
          cost_6: "234",
          cost_7: "233234",
          cost_8: "33434",
          cost_9: "3434",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
        {
          sare_drapping: "87654",
          hdMakeup: "987654",
          cost_3: "345",
          cost_4: "2345",
          cost_5: "2134",
          cost_6: "234",
          cost_7: "233234",
          cost_8: "33434",
          cost_9: "3434",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
        {
          sare_drapping: "98765",
          hdMakeup: "89765",
          cost_3: "98765",
          cost_4: "9876",
          cost_5: "9876",
          cost_6: "897",
          cost_7: "9876",
          cost_8: "987",
          cost_9: "987",
          artist_name: "Queency Makeup",
          id: 0,
          email: "queen99@gmail.com",
        },
      ],
    },
    {
      address: "12/a Madurai",
      name: "Malikam makeup",
      user_email: "malik9@gmail.com",
      artist_password: "malik.123",
      confirm_pass: "malik.123",
      ruppi: "50000",
      localty: "Madurai",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "8",
      image_url: "https://iili.io/H8Iaq1p.jpg",
      upload: [
        {
          title: "gh",
          textarea: "ghjkhgfd",
          uploadname: "Malikam makeup",
          imgurl: "https://iili.io/HXGZAMP.jpg",
          uploader_emial: "malik9@gmail.com",
          id: 0,
        },
        {
          title: "jk",
          textarea: "kj",
          uploadname: "Malikam makeup",
          imgurl: "https://iili.io/HXpVZ9s.jpg",
          uploader_emial: "malik9@gmail.com",
          id: 0,
        },
      ],
      services: [
        { category: "Dewy", values: ["4"], useremail: "malik9@gmail.com" },
      ],
    },
    {
      address: "12/a Theni",
      name: "Prathiusha Makeup",
      user_email: "usha9@gmail.com",
      artist_password: "usha.123",
      confirm_pass: "usha.123",
      ruppi: "50000",
      localty: "Theni",
      makeupname: "Bridal Makeup",
      contact: "6369421401",
      experince_of_artist: "15",
      image_url: "https://iili.io/H8Ia7El.jpg",
      upload: [
        {
          title: "",
          textarea: "",
          uploadname: "",
          imgurl: "",
          uploader_emial: "usha9@gmail.com",
          id: 0,
        },
      ],
      services: [
        { category: "Nude", values: [], useremail: "usha9@gmail.com" },
        { category: "Hd", values: ["2"], useremail: "usha9@gmail.com" },
        { category: "Editorial", values: ["6"], useremail: "usha9@gmail.com" },
        { category: "shymmery", values: ["8"], useremail: "usha9@gmail.com" },
        { category: "celebirity", values: ["7"], useremail: "usha9@gmail.com" },
        { category: "Airbrush", values: ["5"], useremail: "usha9@gmail.com" },
        { category: "Matte", values: ["3"], useremail: "usha9@gmail.com" },
        { category: "Dewy", values: ["4"], useremail: "usha9@gmail.com" },
      ],
      package: [],
    },
    {
      address: "samayapuram",
      name: "Ramya",
      user_email: "ramya@gmail.com",
      artist_password: "Ramya.123",
      confirm_pass: "Ramya.123",
      ruppi: "10000",
      localty: "Trichy",
      makeupname: "BridalMakeup",
      contact: "6369421401",
      experince_of_artist: "13",
      image_url: "https://iili.io/HSxSxoP.jpg",
      packages: [
        {
          "sare_drapping+Advance Makeup per person": "12000",
          "Pro Makeup+Basic hair style Per person": "13000",
          "Jewelery+HD Makeup per person": "15000",
          "Pro Makeup+custumes Per Person": "14000",
          "Bride+BrideMade 2 Person": "15000",
          "Hd Makeup+Hair style per person": "15000",
          "Heavy Makeup+jwelers+custumes": "15000",
          "Hair style+light touchup": "15000",
          "Makeup+mehandi": "0",
          artist_name: "Ramya",
          id: 0,
          email: "ramya@gmail.com",
        },
      ],
      services: [
        { category: "Nude", values: ["1"], useremail: "ramya@gmail.com" },
        { category: "Hd", values: ["2"], useremail: "ramya@gmail.com" },
        { category: "Matte", values: ["3"], useremail: "ramya@gmail.com" },
        { category: "Dewy", values: ["4"], useremail: "ramya@gmail.com" },
        { category: "Airbrush", values: ["5"], useremail: "ramya@gmail.com" },
        { category: "Editorial", values: ["6"], useremail: "ramya@gmail.com" },
        { category: "celebirity", values: ["7"], useremail: "ramya@gmail.com" },
      ],
      booking_records: [
        {
          customer_name: "Madhubala",
          customer_email: "emadhubala1.@gmail.com",
          customer_contact: "23456789876",
          customer_address: "12/A,chennai ,Ambatur",
          event_date: "2023-05-29",
          time: "19:03",
          status: false,
          selected_event: "Bridal",
          se: [
            "sare_drapping+Advance Makeup per person",
            "Pro Makeup+Basic hair style Per person",
          ],
          totla_cost: 37000,
          id: 23,
          selected_artist_for_booking: "Ramya",
        },
      ],
    },
  ],
];

if (localStorage.getItem("card_data")) {
  //   return;
} else {
  localStorage.setItem("card_data", JSON.stringify(card_data));
}

if (localStorage.getItem("artistreviews")) {
  //   return;
} else {
  localStorage.setItem(
    "artistreviews",
    JSON.stringify([
      [
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        {
          input: "Hi how are you?",
          comments: "hi I like you❤❤❤❤❤",
          artists_name: "Madura Makeup",
        },
        {
          input: "Hi your dress is super.",
          comments: "Can we have a catch up!",
          artists_name: "Nadrftuio",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        {
          input: "Nice experince",
          comments: "I liked you",
          artists_name: "Madhu",
        },
        { input: "nice", comments: "nice", artists_name: "Nadrftuio" },
        { input: "nice", comments: "nice", artists_name: "Madhu" },
        {
          input: "nice eperience",
          comments: "Good",
          artists_name: "Nadrftuio",
        },
        {
          input: "nice eperience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        { input: "", comments: "", artists_name: "Madura Makeup" },
        {
          input: "Nice experince",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        { input: "", comments: "", artists_name: "Madura Makeup" },
        {
          input: "It was super experience",
          comments: "asd",
          artists_name: "Madura Makeup",
        },
        {
          input: "Nice experince",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        {
          input: "Madhubala",
          comments: "Nice experince",
          artists_name: "Thulasi Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Wedding makeup",
        },
        {
          input: "dfghjkl;",
          comments: "cvbnm,",
          artists_name: "Thulasi Makeup",
        },
        {
          input: "Wonderful experince",
          comments: "Nice experince",
          artists_name: "Janani Makeup",
        },
        {
          input: "Wonderful experince",
          comments: "Good makeup",
          artists_name: "Queency Makeup",
        },
        { input: "Good work", comments: "Nice", artists_name: "Priya Makeup" },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
      ],
    ])
  );
}

if (localStorage.getItem("upload_details")) {
  //   return;
} else {
  localStorage.setItem(
    "upload_details",
    JSON.stringify([
      [
        {
          title: "jn",
          textarea: "hj",
          uploadname: "madhubala",
          imgurl: "https://iili.io/HXGZAMP.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "madhubala",
          imgurl: "https://iili.io/HXGZAMP.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "kj",
          textarea: "jk",
          uploadname: "jk",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "hj",
          textarea: "jh",
          uploadname: "madhubala",
          imgurl:
            "https://api.vadoo.tv/landing_page?vid=l75bgWZcJFelPqdmjIuXYWmaXPFrHgTd",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
      ],
    ])
  );
}

if (localStorage.getItem("reviews")) {
  //   return;
} else {
  localStorage.setItem(
    "reviews",
    JSON.stringify([
      [
        { name: "vbnm,./", customerReview: " nm,." },
        { name: "xzcvbnm,.", customerReview: " fcgvhbjkl;" },
        { name: "asd", customerReview: "sfdgr" },
        { name: "sdfghj", customerReview: "cvbnm,." },
        { name: "cvbnm", customerReview: "vbnm" },
        { name: "sdfgh", customerReview: "dfgh" },
        { name: "wedwrsty", customerReview: "qwserdstyu" },
        { name: "asdfghjkl", customerReview: "sdfghjkl;" },
        { name: "Madhubala", customerReview: "sdfghujiklo;" },
        { name: "sxdcvfbnm,./", customerReview: "xfcgvjbnmk,." },
        { name: "steffy", customerReview: "cvbnm,." },
        { name: "prathiusha", customerReview: "it is very nice" },
        { name: "sdfg", customerReview: "asdfghjkl;" },
        { name: "sdfghjkl;", customerReview: "sdfghjkl;" },
        { name: "asdfghjkl", customerReview: "rdtfygihjkl;" },
      ],
    ])
  );
}

if (localStorage.getItem("wishlist_dta")) {
  //   return;
} else {
  localStorage.setItem(
    "wishlist_dta",
    JSON.stringify([
      [
        [
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: " Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "vgbn",
            textarea: "bk",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "hfgjkl;'",
            textarea: "cvbnm,./",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "vbnm,./",
            textarea: "vbjnkml,;",
            uploadname: "Madura Makeup",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "GOod ",
            textarea: "Nice",
            uploadname: "Thulasi Makeup",
            imgurl: "https://iili.io/HNYbfwJ.jpg",
            mobilenumber: "91",
          },
          {
            title: "dxfghjkl;",
            textarea: "cvbnm,.",
            uploadname: "Madura Makeup",
            imgurl: "https://iili.io/HNexqhJ.jpg",
            mobilenumber: "91",
          },
        ],
        {
          title: "",
          textarea: "",
          uploadname: "Madura Makeup",
          imgurl: "https://iili.io/HNsPp2e.jpg",
          mobilenumber: "",
        },
        {
          title: "",
          textarea: "",
          uploadname: "Madura Makeup",
          imgurl: "https://iili.io/HNsPp2e.jpg",
          mobilenumber: "91",
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 4,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 5,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 6,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 7,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 8,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 9,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 10,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 11,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 12,
        },
        {
          title: "jk",
          textarea: "jk",
          uploadname: "jk",
          imgurl: "https://iili.io/HNexqhJ.jpg",
          uploader_email: "madhubala1@gmail.com",
          id: 13,
        },
        {
          title: "bv",
          textarea: "bv",
          uploadname: "madhubala",
          imgurl: "https://vimeo.com/820261491?share=copy",
          uploader_email: "madhubala1@gmail.com",
          id: 14,
        },
        {
          title: "bv",
          textarea: "bv",
          uploadname: "madhubala",
          imgurl: "https://streamable.com/g5anf5",
          uploader_email: "madhubala1@gmail.com",
          id: 15,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 15,
          title: "Malikam makeup",
          image: "../../assets/images/new-1.jpg",
          price: "13000 per function",
          status: false,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 16,
          title: "Prathiusha Makeup",
          image: "../../assets/images/7357084cd7e989a7ea629c20a0ad9c2a.jpg",
          price: "12,000 per function",
          status: false,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 17,
          title: "subha makeup",
          image: "../../assets/images/imagee.webp",
          price: "15000 per function",
          status: false,
        },
      ],
    ])
  );
}
