let card_data = [
  {
    address: "trichy",
    name: "Madura Makeup",
    user_email: "madhubala@gmail.com",
    artist_password: "bn",
    confirm_pass: "bn",
    ruppi: "10000",
    localty: "chennai",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "12",
    image_url: "https://iili.io/HXGZPUu.jpg",
  },
  {
    address: "chennai",
    name: "steffy Makeup",
    user_email: "madhubala1@gmail.com",
    artist_password: "78",
    confirm_pass: "78",
    ruppi: "10000",
    localty: "chennai",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "12",
    image_url: "https://iili.io/HXGZPUu.jpg",
  },
  {
    address: "12/a kanyakumari",
    name: "subha makeup",
    user_email: "madhubala99@gmail.com",
    artist_password: "Madhu.06",
    confirm_pass: "Madhu.06",
    ruppi: "10000",
    localty: "Kanyakumari",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "12",
    image_url: "https://iili.io/H8I7QKN.jpg",
  },
  {
    address: "Trichy,samyapuram",
    name: "Janani Makeup",
    user_email: "janani@gmail.com",
    artist_password: "jan123.",
    confirm_pass: "jan123.",
    ruppi: "15000",
    localty: "Trichy",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "11",
    image_url: "https://iili.io/H8IYufV.jpg",
  },
  {
    address: "12/a salem",
    name: "Priya Makeup",
    user_email: "priya99@gmail.com",
    artist_password: "priya.123",
    confirm_pass: "priya.123",
    ruppi: "18000",
    localty: "salem",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "8",
    image_url: "https://iili.io/H8IYEsR.jpg",
  },
  {
    address: "12/a namakal",
    name: "Queency Makeup",
    user_email: "queen99@gmail.com",
    artist_password: "queen.123",
    confirm_pass: "queen.123",
    ruppi: "18000",
    localty: "namakal",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "8",
    image_url: "https://iili.io/H8IYezG.webp",
  },
  {
    address: "12/a Madurai",
    name: "Malikam makeup",
    user_email: "malik9@gmail.com",
    artist_password: "malik.123",
    confirm_pass: "malik.123",
    ruppi: "50000",
    localty: "Madurai",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "8",
    image_url: "https://iili.io/H8Iaq1p.jpg",
  },
  {
    address: "12/a Theni",
    name: "Prathiusha Makeup",
    user_email: "usha9@gmail.com",
    artist_password: "usha.123",
    confirm_pass: "usha.123",
    ruppi: "50000",
    localty: "Theni",
    makeupname: "Bridal Makeup",
    contact: "6369421401",
    experince_of_artist: "15",
    image_url: "https://iili.io/H8Ia7El.jpg",
  },
];

if (localStorage.getItem("card_data")) {
  //   return;
} else {
  localStorage.setItem("card_data", JSON.stringify(card_data));
}

if (localStorage.getItem("artistreviews")) {
  //   return;
} else {
  localStorage.setItem(
    "artistreviews",
    JSON.stringify([
      [
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        {
          input: "Hi how are you?",
          comments: "hi I like you❤❤❤❤❤",
          artists_name: "Madura Makeup",
        },
        {
          input: "Hi your dress is super.",
          comments: "Can we have a catch up!",
          artists_name: "Nadrftuio",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        {
          input: "Nice experince",
          comments: "I liked you",
          artists_name: "Madhu",
        },
        { input: "nice", comments: "nice", artists_name: "Nadrftuio" },
        { input: "nice", comments: "nice", artists_name: "Madhu" },
        {
          input: "nice eperience",
          comments: "Good",
          artists_name: "Nadrftuio",
        },
        {
          input: "nice eperience",
          comments: "The makeup artist was super",
          artists_name: "Nadrftuio",
        },
        { input: "", comments: "", artists_name: "Madura Makeup" },
        {
          input: "Nice experince",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        { input: "", comments: "", artists_name: "Madura Makeup" },
        {
          input: "It was super experience",
          comments: "asd",
          artists_name: "Madura Makeup",
        },
        {
          input: "Nice experince",
          comments: "The makeup artist was super",
          artists_name: "Madura Makeup",
        },
        {
          input: "Madhubala",
          comments: "Nice experince",
          artists_name: "Thulasi Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Wedding makeup",
        },
        {
          input: "dfghjkl;",
          comments: "cvbnm,",
          artists_name: "Thulasi Makeup",
        },
        {
          input: "Wonderful experince",
          comments: "Nice experince",
          artists_name: "Janani Makeup",
        },
        {
          input: "Wonderful experince",
          comments: "Good makeup",
          artists_name: "Queency Makeup",
        },
        { input: "Good work", comments: "Nice", artists_name: "Priya Makeup" },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
        {
          input: "It was super experience",
          comments: "The makeup artist was super",
          artists_name: "Priya Makeup",
        },
      ],
    ])
  );
}

if (localStorage.getItem("upload_details")) {
  //   return;
} else {
  localStorage.setItem(
    "upload_details",
    JSON.stringify([
      [
        {
          title: "jn",
          textarea: "hj",
          uploadname: "madhubala",
          imgurl: "https://iili.io/HXGZAMP.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "madhubala",
          imgurl: "https://iili.io/HXGZAMP.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "kj",
          textarea: "jk",
          uploadname: "jk",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
        {
          title: "hj",
          textarea: "jh",
          uploadname: "madhubala",
          imgurl:
            "https://api.vadoo.tv/landing_page?vid=l75bgWZcJFelPqdmjIuXYWmaXPFrHgTd",
          uploader_emial: "madhubala1@gmail.com",
          id: 0,
        },
      ],
    ])
  );
}

if (localStorage.getItem("reviews")) {
  //   return;
} else {
  localStorage.setItem(
    "reviews",
    JSON.stringify([
      [
        { name: "vbnm,./", customerReview: " nm,." },
        { name: "xzcvbnm,.", customerReview: " fcgvhbjkl;" },
        { name: "asd", customerReview: "sfdgr" },
        { name: "sdfghj", customerReview: "cvbnm,." },
        { name: "cvbnm", customerReview: "vbnm" },
        { name: "sdfgh", customerReview: "dfgh" },
        { name: "wedwrsty", customerReview: "qwserdstyu" },
        { name: "asdfghjkl", customerReview: "sdfghjkl;" },
        { name: "Madhubala", customerReview: "sdfghujiklo;" },
        { name: "sxdcvfbnm,./", customerReview: "xfcgvjbnmk,." },
        { name: "steffy", customerReview: "cvbnm,." },
        { name: "prathiusha", customerReview: "it is very nice" },
        { name: "sdfg", customerReview: "asdfghjkl;" },
        { name: "sdfghjkl;", customerReview: "sdfghjkl;" },
        { name: "asdfghjkl", customerReview: "rdtfygihjkl;" },
      ],
    ])
  );
}

if (localStorage.getItem("wishlist_dta")) {
  //   return;
} else {
  localStorage.setItem(
    "wishlist_dta",
    JSON.stringify([
      [
        [
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: " Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "SADFGHJKAETRYUIO",
            textarea: "FGHJKL;",
            uploadname: "Nadrftuio",
            imgurl: "https://iili.io/HXDBIh7.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "asdfghjkoiuytrewqertyui",
            textarea: "dfghjkloiuytre",
            uploadname: "dsfghjkuytrewqertyuio",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "ghjklk,m",
            textarea: "vcbnm,mn",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "vgbn",
            textarea: "bk",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "hfgjkl;'",
            textarea: "cvbnm,./",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "dfghjkl;'",
            textarea: "dxfcgvhbjnkml,;.'/",
            uploadname: "Madhu",
            imgurl: "https://iili.io/HXpVZ9s.jpg",
            mobilenumber: "91",
          },
          {
            title: "vbnm,./",
            textarea: "vbjnkml,;",
            uploadname: "Madura Makeup",
            imgurl: "https://iili.io/HXGZAMP.jpg",
            mobilenumber: "91",
          },
          {
            title: "GOod ",
            textarea: "Nice",
            uploadname: "Thulasi Makeup",
            imgurl: "https://iili.io/HNYbfwJ.jpg",
            mobilenumber: "91",
          },
          {
            title: "dxfghjkl;",
            textarea: "cvbnm,.",
            uploadname: "Madura Makeup",
            imgurl: "https://iili.io/HNexqhJ.jpg",
            mobilenumber: "91",
          },
        ],
        {
          title: "",
          textarea: "",
          uploadname: "Madura Makeup",
          imgurl: "https://iili.io/HNsPp2e.jpg",
          mobilenumber: "",
        },
        {
          title: "",
          textarea: "",
          uploadname: "Madura Makeup",
          imgurl: "https://iili.io/HNsPp2e.jpg",
          mobilenumber: "91",
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 4,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 5,
        },
        {
          title: "",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 6,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 7,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 8,
        },
        {
          title: "hj",
          textarea: "fghjk",
          uploadname: "Madhubala",
          imgurl: "https://iili.io/HNYbfwJ.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 9,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 10,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 11,
        },
        {
          title: "hj",
          textarea: "hj",
          uploadname: "rtyuio",
          imgurl: "https://iili.io/HNsiITv.jpg",
          mobilenumber: null,
          uploader_emial: "madhubala1@gmail.com",
          id: 12,
        },
        {
          title: "jk",
          textarea: "jk",
          uploadname: "jk",
          imgurl: "https://iili.io/HNexqhJ.jpg",
          uploader_email: "madhubala1@gmail.com",
          id: 13,
        },
        {
          title: "bv",
          textarea: "bv",
          uploadname: "madhubala",
          imgurl: "https://vimeo.com/820261491?share=copy",
          uploader_email: "madhubala1@gmail.com",
          id: 14,
        },
        {
          title: "bv",
          textarea: "bv",
          uploadname: "madhubala",
          imgurl: "https://streamable.com/g5anf5",
          uploader_email: "madhubala1@gmail.com",
          id: 15,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 15,
          title: "Malikam makeup",
          image: "../../assets/images/new-1.jpg",
          price: "13000 per function",
          status: false,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 16,
          title: "Prathiusha Makeup",
          image: "../../assets/images/7357084cd7e989a7ea629c20a0ad9c2a.jpg",
          price: "12,000 per function",
          status: false,
        },
        {
          email_user_wishlist: "hemanthm4@gmail.com",
          user_name: "HemanathM",
          id_wishlist: 17,
          title: "subha makeup",
          image: "../../assets/images/imagee.webp",
          price: "15000 per function",
          status: false,
        },
      ],
    ])
  );
}
